on:
  pull_request:
    branches:
      - develop
      - main
      - next
      - release
jobs:
  commit-lint:
    uses: ./.github/workflows/commit-lint.yml
  unit-test:
    needs: commit-lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./yarn.lock

      - name: run unit test
        run: |
          yarn
          yarn test
  build-check:
    # The type of runner that the job will run on
    needs: unit-test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./yarn.lock

      - name: build
        run: |
          yarn
          yarn build
