name: release-change-log
on:
  push:
    branches:
      - main
      - develop
jobs:
  release:
    name: release-change-log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Build the package
        run: yarn && yarn build
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
